FROM mcr.microsoft.com/devcontainers/base:ubuntu

ENV MY_VAR="SOME_VAL"

EXPOSE 3000

# The volume is already mapped | shared
# No need to cache, create volume or copy anything

CMD ["echo", "[Codesandbox] Installing devcontainer"]